### ISSUE TITLE
[Android] Follow me feature

### ISSUE THREAD

**Issue by sylvioalves** [Parrot-Developers/ARSDKBuildUtils#46]
Hi, 

Are we able to implement a follow me based on gps position? I think that using (cheating) the gohome implementation could work, but it is not the case.

(Can we work out on the firmware by ourselves? Is it opensourced?)

Thanks.

Sylvio

**Comment by djavan-bertrand** [comment]
Hi !
No, the firmware is not opensourced. 
With the SDK, you could send piloting commands and analysing the gps data from the drone to know when to stop or continue.

Regards, 
Djavan

**Comment by sylvioalves** [comment]
I thought the same way.

However, It seems that PCMD callback does not return with PSI data. It would be very helpful to get drone's compass (or at least where it is headed to...).

Regards,
Sylvio Alves

**Comment by djavan-bertrand** [comment]
The attitude of the drone give you the information you need.
You can add the callback ARCOMMANDS_Decoder_SetARDrone3PilotingStateAttitudeChangedCallback. It gives you the roll, the pitch and the **yaw** (orientation of the drone) in radian.

Regards, 
Djavan

**Comment by sylvioalves** [comment]
Hi, 

I think you mean this callback?
onARDrone3PilotingStateAttitudeChangedUpdate(float roll, float pitch, float yaw)

Thanks.

Sylvio

**Comment by djavan-bertrand** [comment]
Yes, indeed.

Regards, 
Djavan

**Comment by PatrickGoettert** [comment]
Hi,

I have been trying to interpret the data that comes from referred callback (onARDrone3PilotingStateAttitudeChangedUpdate), but I noticed that the Yaw is not reliable...

First of all - it is not a flaw - by design the drone always takes the heading it starts as a reference (and starts at zero for that orientation). If you made a 360degrees turn it should have zero again at the yaw variable.
But after a few minutes flight, when you land it in the same orientation(same place and heading) that you took off, it SHOULD have the same YAW in that callback, but it does not. It usually is an arbitrary number, probably based on the characteristics of your flight. I've got errors ranging from 20degrees up to 170degrees.

So I started my testing, I compiled the frameworks for iOS, and added to the "BebopDronePiloting" the callback to ARCOMMANDS_Decoder_SetARDrone3PilotingStateAttitudeChangedCallback, so that I could watch how the variables YAW, PITCH and ROLL behaved. To convert these variables to degrees, I used the formula: (yaw * 180 / M_PI) = YawInDegrees.
I made a few flights, but I also tried just rotating the bebop with my own hands over a wooden table (so as to not interfere magnetically), which made it much easier to observe just one variable at a time.

For the tests with the YAW variable, the bebop remained with all four "legs" touching the table at all times, so as to PITCH and ROLL to remain basically at zero.
Here is what I found out - I just analysed the YAW variable.
1.If you turn your Bebop "quickly", it usually reads approximately correctly the yaw - I made several 90/180/360 degrees rotation, which resulted in a small error.
2.HERE IS THE IMPORTANT PART: if you turn your bebop (yaw) very slowly (say 15 seconds to 90 degrees), the yaw variable will just "perceive" a much smaller rotation. In my tests, a 90 degree rotation produced even as little as a 10 degree "perception" on the yaw variable.
3.Experience number 2 is confirmed if you choose one leg of the bebop, fix its position to the table and rotate the bebop around that leg slowly. This experience produced the worst results, a 90 degrees turn produced a variation of 5 degrees on the yaw.

Is there any way to have access to the magnetometer data of the bebop? The heading basically cant be computed by any means - even though you could compute TRACKING by comparing positions, but only when the bebop is moving in one direction.
Is there any more reliable way to check bebop's direction?
Thanks in advance,
Patrick Goettert

**Comment by djavan-bertrand** [comment]
Hi, 
thanks for this feedback. Did you calibrate your drone right before your tests (you can calibrate it with the FreeFlight3 app) ?
Regards, 
Djavan

**Comment by PatrickGoettert** [comment]
Hi!
I did calibrate the drone right before I tested it, using the freeflight3 app.
My drone is on the last firmware version available.
I also tried with multiple (3) bebops, all uptodate firmwarewise, all with the exact same result.
As you can see in this other issue:
Rotate the drone to magnetic north #32
( https://github.com/Parrot-Developers/Samples/issues/32 )
This error is also reported by other users, that user reports a 30+ error after a simple 360degrees turn!

To further explain, By rotating the bebop very slowly, I was able to make the yaw data become less responsive rotating clock/countrrclockwise, so the yaw "drifted" east AND westbound, depending on the previous movement I made.
My hipothesis is that the yaw difference is not being computed by the magnetometer, but by some accelerometer or by a gyro which does not update frequently enough to be able to make a reliable calculation of the yaw. These things would probably produce the result I see.
 A magnetometer reading would only be affected by magnetic forces reaching the sensor, and would yield the results one would expect from the YAW variable.

Is there anyway we can have access to that magnetometer data? I would be very useful to compute ANY kind of navigation.
If not yet available, is there any other way to compute the heading in RELIABLE way?
Thanks again,
Best regards, 
Patrick Goettert

**Comment by djavan-bertrand** [comment]
I'll give this information to the firmware team, see if they can help you. Thanks again for this feedback and analysis.

No, you can't access the raw magnetometer data. The values received in the callback I gave you should be reliable, we will work to get it done :)

Regards, 
Djavan

**Comment by PatrickGoettert** [comment]
Just to let you know that the blackbox logs the needed information :)
